apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
  namespace: default
spec:
  containers:
    - name: configmap-containers
      image: nginx:latest
      volumeMounts:
        - name: ngx-config
          mountPath: /etc/nginx/conf.d/vhost.conf
          subPath: vhost.conf
          readOnly: true
        - name: ngx-html
          mountPath: /usr/share/nginx/html/configmap.html
          subPath: configmap.html
          readOnly: true
  volumes:
    - name: ngx-config
      configMap:
        name: nginx-config-files
    - name: ngx-html
      configMap:
        name: nginx-html-files
